[package]
name = "rs"
version = "0.0.1"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poseidon-rs = "0.0.2"
rustc-hex = "1.0.0"
