[package]
name = "poseidon-rs-examples"
version = "0.0.1"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"

[dependencies]
ff = {package="ff_ce" , version="0.11", features = ["derive"]}
poseidon-rs = "0.0.4"
rustc-hex = "1.0.0"
num = "0.2.0"
num-bigint = "0.2.2"
